comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
        
codecov: 
 token: f27459fe-1701-48f3-bffd-2df82e161559
